### ISSUE TITLE
I found bug

### ISSUE THREAD

**Issue by gryzzlaycutzy121** [archanaberry/Gacha-Design-Studio#5]
DL untuk yang di download game nya agar portabel di hp maupun pc yang dimainkan untuk offline
HS untuk dihosting agar bisa publish ataupun publik dan bisa online dan banyak dukungan backend nya

Tolong perbaiki bug tombol impor, ekspor nya susah dipencet dan berikan jeda 0.5ms untuk memunculkan popup, dan juga kedua tombol ini sulit di pojok kanan kan di atas 100% X 100% Y dan berikan jarak kedua tombol ini sebesar 2mm
Lalu tombol dari 1 sampai 6 tolong diperbaiki animasi dan layout nya karena ga normal kliking nya.
perbaiki agar bisa horizontal dan responsif di vertikal maupun horizontal,
pasangin pemutar music yang menyetel lagu secara acak dan buatkan layar sentuh di studio pose nya.

**Comment by jacktor-stan** [comment]
Akan ditangani jika memungkinkan

**Comment by archanaberry** [comment]
Aku anggap sudah selesai karena sudah di fix.
Nanti kalau ada bug bisa dilaporkan ｡⁠◕⁠‿⁠◕⁠｡
